log non runtime exceptions in JawrServlet, such as NoClassDefFoundError, which may be thrown if rhino, lesscss or some other jars are missing in a project